apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
    version: v2
  name: frontend
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
     labels:
       service: frontend
       version: v2
       api: external
    spec:
      containers:
      - image: moemad711/udacity-frontend:local
        name: frontend
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - touch
            - /tmp/healthy
          initialDelaySeconds:  5
          periodSeconds: 5
          successThreshold: 1          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
