apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
    version: v2
  name: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
      matchLabels:
        service: frontend
  template:
    metadata:
      labels:
        service: frontend
        version: v2
        api: external        
    spec:
      containers:
      - image: moemad711/udacity-frontend:local
        name: frontend
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - touch
            - /tmp/healthy
          initialDelaySeconds:  5
          periodSeconds: 5
          successThreshold: 1          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always

