apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
    #version: v2
  name: reverseproxy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
      matchLabels:
        service: reverseproxy
        #version: v2
  template:
    metadata:
      labels:
        service: reverseproxy
        #version: v2
    spec:
      containers:
      - image: moemad711/reverseproxy
        name: reverseproxy
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds:  5
          periodSeconds: 5
          successThreshold: 1          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


